name: Container Build

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]
  workflow_call:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  security-events: write
  pull-requests: write

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Build and Push Container
        uses: wgtechlabs/container-build-flow-action@d64e8cce8fa7694f4a3047e8384b4d21773cd41d # v1.7.1
        with:
          registry: both
          dockerhub-username: ${{ secrets.DOCKER_HUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          ghcr-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
          trivy-severity: CRITICAL
          fail-on-vulnerability: true
